# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr =np.array(my_list)

In [4]:
arr 

array([1, 2, 3])

In [5]:
print(arr)

[1 2 3]


In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
dimension = np.array(my_mat)

In [8]:
dimension

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5,5,5)

array([[[0.92550511, 0.45586004, 0.17186073, 0.6734462 , 0.13678275],
        [0.18273342, 0.73249789, 0.34498751, 0.19174534, 0.95762611],
        [0.62358245, 0.76251988, 0.81946259, 0.96818285, 0.5243727 ],
        [0.52734707, 0.89930996, 0.00971824, 0.27688168, 0.51201785],
        [0.84067653, 0.69852104, 0.3782362 , 0.15300064, 0.86172937]],

       [[0.15086683, 0.14861713, 0.03895842, 0.44243326, 0.40246792],
        [0.7945888 , 0.65931709, 0.91251488, 0.77015664, 0.93052527],
        [0.25313128, 0.65462883, 0.00284991, 0.39775859, 0.76230134],
        [0.51611643, 0.81130421, 0.05112587, 0.76468398, 0.36461491],
        [0.95152523, 0.94223576, 0.78391749, 0.14665925, 0.25702328]],

       [[0.04424484, 0.30358549, 0.73763268, 0.4271702 , 0.5193483 ],
        [0.35601166, 0.95816869, 0.18996584, 0.38272186, 0.24374119],
        [0.68030663, 0.01336329, 0.38018402, 0.24194495, 0.54635612],
        [0.40872273, 0.3407535 , 0.19855219, 0.75517934, 0.03785643],
        [0.24806

In [18]:
np.random.rand(5,5)

array([[0.35578702, 0.4697389 , 0.66553646, 0.35897582, 0.85575727],
       [0.40214581, 0.78677549, 0.3150064 , 0.90975106, 0.52484508],
       [0.55115403, 0.82434282, 0.19613875, 0.71403824, 0.39996977],
       [0.93966268, 0.24721778, 0.24820679, 0.34158035, 0.40730253],
       [0.02602231, 0.04424897, 0.80397127, 0.58078465, 0.33806495]])

In [19]:
np.random.randn(3,3,3)

array([[[ 1.25644292, -2.87606639,  0.38485834],
        [ 1.59303121,  1.26564928,  0.62197607],
        [ 0.1128377 ,  1.64422656, -0.07160157]],

       [[-1.24599477,  1.91067347,  0.53941337],
        [ 0.95463805,  0.22937725,  0.07783117],
        [-0.65060932, -0.23093407, -1.03633861]],

       [[-1.31912045, -1.47696097, -0.19607936],
        [ 0.33256411, -0.49791948,  1.32510522],
        [-2.57213646,  1.78855971, -2.46886355]]])

In [20]:
rearrange = np.random.randint(3,100,10)

In [21]:
arr = np.arange(25)

In [22]:
ranarr = np.random.randint(3,100,10)

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr = ranarr.reshape(5,2)

In [25]:
ranarr

array([[99, 38],
       [41, 52],
       [22, 18],
       [21, 83],
       [39, 37]])

In [26]:
ranarr.max()

99

In [27]:
ranarr.min()

18

In [28]:
ranarr.argmax()

0

In [29]:
ranarr.shape

(5, 2)

In [30]:
arr.shape

(25,)

In [31]:
ranarr.dtype

dtype('int64')

# Numpy indexing and selection

In [32]:
arr = np.arange(11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [35]:
np.arange(11)[8]

8

In [36]:
arr[2]

2

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[8:]

array([ 8,  9, 10])

In [39]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
arr[0:5] = 100

In [41]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [42]:
arr[:]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
arr = np.arange(0,11)

In [44]:
slice_of_arr = arr[0:6]

In [45]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [46]:
slice_of_arr[:]=99

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr_copy = arr.copy()

In [50]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
slice_of_copy = arr_copy[3:6]

In [52]:
slice_of_copy[:] = 1010

In [53]:
slice_of_copy

array([1010, 1010, 1010])

In [54]:
arr_copy

array([  99,   99,   99, 1010, 1010, 1010,    6,    7,    8,    9,   10])

# 2D array indexing

In [55]:
arr_2d = np.arange(5,46,5).reshape(3,3)

In [56]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
arr_2d[1][2]

30

In [58]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
arr = np.arange(1,11)

In [60]:
bool_arr = arr > 5

In [61]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[arr<4]

array([1, 2, 3])

In [66]:
arr_2dn = np.arange(50).reshape(5,10)

In [67]:
arr_2dn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:
arr_2dn[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
arr_2dn[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [70]:
arr_2dn[2:,5:8]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [71]:
arr_2dn[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [72]:
arr_2dn[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [73]:
arr_2dn[0][1]

1

In [74]:
arr_2dn[2:][:1]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [75]:
arr_2dn[3:,7:10]

array([[37, 38, 39],
       [47, 48, 49]])

In [76]:
array = np.arange(0,11)

In [77]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
array = array * array

In [79]:
array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [80]:
array / array

/var/folders/9b/q0txn0fd5qj57z36hsjf2yxh0000gn/T/ipykernel_42694/3681233016.py:1: RuntimeWarning: invalid value encountered in divide
  array / array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [81]:
array **2

array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000])

In [82]:
import numpy as np

In [83]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [86]:
arr = (np.ones(10))*5

In [87]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [88]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [89]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [90]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.random.rand(1,26)

array([[0.76455142, 0.7557126 , 0.10125972, 0.80871335, 0.67267596,
        0.91118353, 0.18385619, 0.34430677, 0.36400088, 0.19376745,
        0.80649741, 0.88939876, 0.56405396, 0.95813273, 0.10884434,
        0.09302579, 0.21527659, 0.69006636, 0.1432932 , 0.89172326,
        0.10662648, 0.52211039, 0.92115522, 0.21532457, 0.69499158,
        0.74867502]])

In [93]:
np.arange(1,100)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [94]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [95]:
mat = np.arange(1,26).reshape(5,5)

In [96]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [97]:
mat[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [98]:
print("new line added")

new line added


NEW MARKDOWN ADDED

In [99]:
print("new commit test")

new commit test


In [100]:
print("latest commit today")

latest commit today


In [101]:
np.arange(2,4)

array([2, 3])