# NumPy Arrays

In [10]:
my_list = [1,2,3]

In [11]:
import numpy as np

In [12]:
arr =np.array(my_list)

In [13]:
arr 

array([1, 2, 3])

In [14]:
print(arr)

[1 2 3]


In [15]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
dimension = np.array(my_mat)

In [17]:
dimension

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5,5,5)

array([[[0.44778194, 0.45030665, 0.74825842, 0.4117096 , 0.36277009],
        [0.26176952, 0.89780197, 0.78750289, 0.21200947, 0.55575018],
        [0.61317497, 0.09229179, 0.3127746 , 0.20962451, 0.46284249],
        [0.21883265, 0.75922711, 0.80159078, 0.6693466 , 0.14302936],
        [0.10523324, 0.20473434, 0.57782867, 0.61287296, 0.14512626]],

       [[0.68016437, 0.8771312 , 0.97061674, 0.16592681, 0.18761458],
        [0.59039776, 0.77494399, 0.33305088, 0.14588507, 0.4372936 ],
        [0.99419033, 0.61701635, 0.74390436, 0.32135348, 0.91169599],
        [0.25442881, 0.48083069, 0.97840152, 0.94422869, 0.4620667 ],
        [0.33982158, 0.52482343, 0.29772045, 0.27371096, 0.76965358]],

       [[0.04471317, 0.17661005, 0.27285861, 0.01888982, 0.04353154],
        [0.51145718, 0.19355675, 0.62916321, 0.01294196, 0.2563211 ],
        [0.52364581, 0.1850735 , 0.27682422, 0.03767362, 0.90630827],
        [0.32278237, 0.90782527, 0.73362522, 0.76217385, 0.76656029],
        [0.79962

In [27]:
np.random.rand(5,5)

array([[0.38593624, 0.84733829, 0.01520114, 0.33222037, 0.92851668],
       [0.69691506, 0.74379993, 0.32483113, 0.46272824, 0.55864111],
       [0.33383627, 0.93696724, 0.5142104 , 0.6732197 , 0.90592551],
       [0.59428074, 0.18491329, 0.88451318, 0.70498248, 0.41652714],
       [0.05174314, 0.86800441, 0.44158256, 0.15090738, 0.29342491]])

In [28]:
np.random.randn(3,3,3)

array([[[ 0.05994065, -0.2839484 ,  1.39484554],
        [ 1.12690107,  0.29203069,  0.34070103],
        [-0.60948263,  2.58185421,  0.15338399]],

       [[-0.62519493,  0.20597382, -0.94278043],
        [ 0.12017873, -0.87760364, -0.18171102],
        [ 0.3386804 , -0.59104487, -0.74888827]],

       [[ 0.04813789, -0.5041963 , -0.18217641],
        [ 1.97459114, -0.00570931, -1.02402395],
        [-0.29964447,  1.29115787,  0.56694834]]])

In [29]:
rearrange = np.random.randint(3,100,10)

In [30]:
arr = np.arange(25)

In [31]:
ranarr = np.random.randint(3,100,10)

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr = ranarr.reshape(5,2)

In [34]:
ranarr

array([[ 7, 43],
       [59, 51],
       [48, 14],
       [45, 22],
       [31, 82]])

In [35]:
ranarr.max()

82

In [36]:
ranarr.min()

7

In [37]:
ranarr.argmax()

9

In [38]:
ranarr.shape

(5, 2)

In [39]:
arr.shape

(25,)

In [40]:
ranarr.dtype

dtype('int64')

# Numpy indexing and selection

In [41]:
arr = np.arange(11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [44]:
np.arange(11)[8]

8

In [45]:
arr[2]

2

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[8:]

array([ 8,  9, 10])

In [48]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
arr[0:5] = 100

In [50]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr[:]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [52]:
arr = np.arange(0,11)

In [53]:
slice_of_arr = arr[0:6]

In [54]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [55]:
slice_of_arr[:]=99

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr_copy = arr.copy()

In [59]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
slice_of_copy = arr_copy[3:6]

In [61]:
slice_of_copy[:] = 1010

In [62]:
slice_of_copy

array([1010, 1010, 1010])

In [63]:
arr_copy

array([  99,   99,   99, 1010, 1010, 1010,    6,    7,    8,    9,   10])

# 2D array indexing

In [64]:
arr_2d = np.arange(5,46,5).reshape(3,3)

In [65]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
arr_2d[1][2]

30

In [67]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [68]:
arr = np.arange(1,11)

In [69]:
bool_arr = arr > 5

In [70]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [72]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[arr<4]

array([1, 2, 3])

In [75]:
arr_2dn = np.arange(50).reshape(5,10)

In [76]:
arr_2dn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
arr_2dn[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [78]:
arr_2dn[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [79]:
arr_2dn[2:,5:8]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [80]:
arr_2dn[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
arr_2dn[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [84]:
arr_2dn[0][1]

1

In [86]:
arr_2dn[2:][:1]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [88]:
arr_2dn[3:,7:10]

array([[37, 38, 39],
       [47, 48, 49]])

In [90]:
array = np.arange(0,11)

In [91]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
array = array * array

In [98]:
array

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [99]:
array / array

/var/folders/9b/q0txn0fd5qj57z36hsjf2yxh0000gn/T/ipykernel_1547/3681233016.py:1: RuntimeWarning: invalid value encountered in divide
  array / array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
array **2

array([     0,     16,    256,   1296,   4096,  10000,  20736,  38416,
        65536, 104976, 160000])

In [101]:
import numpy as np

In [103]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [104]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [107]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [108]:
arr = (np.ones(10))*5

In [109]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [110]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [112]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [114]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
np.random.rand(1,26)

array([[0.67425135, 0.76069868, 0.20716892, 0.84380455, 0.10023321,
        0.02266178, 0.67795203, 0.13441408, 0.12645962, 0.15605943,
        0.63601684, 0.8825465 , 0.10376103, 0.64568415, 0.91540221,
        0.94041052, 0.70753439, 0.15258044, 0.41366692, 0.12818395,
        0.05355819, 0.83710012, 0.23705029, 0.85434795, 0.57249742,
        0.15349281]])

In [124]:
np.arange(1,100)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [125]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [126]:
mat = np.arange(1,26).reshape(5,5)

In [127]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [132]:
mat[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [2]:
print("new line added")

new line added


NEW MARKDOWN ADDED

In [4]:
print("new commit test")

new commit test


In [ ]:
asadasdvhbjsakdasdhbj