# K-Nearest Neighbor Classification
K-nearest neighbors (KNN) is a supervised machine learning algorithm used for classification and regression tasks. It's a non-parametric method, meaning it doesn't make any assumptions about the underlying data distribution.
1. We select the K value
2. K value is the number of nearest neighbor
3. If K is 5 then the nearest 5 neighbor distance is calculated (neighbor = dataset)
4. Find the category of the 5 neighbor
5. Max category will be euqal to the same classification
6. Distance can be calculated by Eucledian and Manhattan Distance
7. There might be biasness due to imbalanced datasets and outliers


In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [92]:
df = pd.read_csv("Datasets/Classified Data.csv")

In [93]:
df

Unnamed: 0       WTT       PTI       EQW       SBI       LQE       QWG  \
0             0  0.913917  1.162073  0.567946  0.755464  0.780862  0.352608   
1             1  0.635632  1.003722  0.535342  0.825645  0.924109  0.648450   
2             2  0.721360  1.201493  0.921990  0.855595  1.526629  0.720781   
3             3  1.234204  1.386726  0.653046  0.825624  1.142504  0.875128   
4             4  1.279491  0.949750  0.627280  0.668976  1.232537  0.703727   
..          ...       ...       ...       ...       ...       ...       ...   
995         995  1.010953  1.034006  0.853116  0.622460  1.036610  0.586240   
996         996  0.575529  0.955786  0.941835  0.792882  1.414277  1.269540   
997         997  1.135470  0.982462  0.781905  0.916738  0.901031  0.884738   
998         998  1.084894  0.861769  0.407158  0.665696  1.608612  0.943859   
999         999  0.837460  0.961184  0.417006  0.799784  0.934399  0.424762   

          FDJ       PJF       HQE       NXJ  TARGET CLASS  
0    0.759697  0.643798  0.879422  1.231409             1  
1    0.675334  1.013546  0.621552  1.492702             0  
2    1.626351  1.154483  0.957877  1.285597             0  
3    1.409708  1.380003  1.522692  1.153093             1  
4    1.115596  0.646691  1.463812  1.419167             1  
..        ...       ...       ...       ...           ...  
995  0.746811  0.319752  1.117340  1.348517             1  
996  1.055928  0.713193  0.958684  1.663489             0  
997  0.386802  0.389584  0.919191  1.385504             1  
998  0.855806  1.061338  1.277456  1.188063             1  
999  0.778234  0.907962  1.257190  1.364837             1  

[1000 rows x 12 columns]

In [94]:
df.describe()

Unnamed: 0          WTT          PTI          EQW          SBI  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean    499.500000     0.949682     1.114303     0.834127     0.682099   
std     288.819436     0.289635     0.257085     0.291554     0.229645   
min       0.000000     0.174412     0.441398     0.170924     0.045027   
25%     249.750000     0.742358     0.942071     0.615451     0.515010   
50%     499.500000     0.940475     1.118486     0.813264     0.676835   
75%     749.250000     1.163295     1.307904     1.028340     0.834317   
max     999.000000     1.721779     1.833757     1.722725     1.634884   

               LQE          QWG          FDJ          PJF          HQE  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      1.032336     0.943534     0.963422     1.071960     1.158251   
std       0.243413     0.256121     0.255118     0.288982     0.293738   
min       0.315307     0.262389     0.295228     0.299476     0.365157   
25%       0.870855     0.761064     0.784407     0.866306     0.934340   
50%       1.035824     0.941502     0.945333     1.065500     1.165556   
75%       1.198270     1.123060     1.134852     1.283156     1.383173   
max       1.650050     1.666902     1.713342     1.785420     1.885690   

               NXJ  TARGET CLASS  
count  1000.000000    1000.00000  
mean      1.362725       0.50000  
std       0.204225       0.50025  
min       0.639693       0.00000  
25%       1.222623       0.00000  
50%       1.375368       0.50000  
75%       1.504832       1.00000  
max       1.893950       1.00000

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    1000 non-null   int64  
 1   WTT           1000 non-null   float64
 2   PTI           1000 non-null   float64
 3   EQW           1000 non-null   float64
 4   SBI           1000 non-null   float64
 5   LQE           1000 non-null   float64
 6   QWG           1000 non-null   float64
 7   FDJ           1000 non-null   float64
 8   PJF           1000 non-null   float64
 9   HQE           1000 non-null   float64
 10  NXJ           1000 non-null   float64
 11  TARGET CLASS  1000 non-null   int64  
dtypes: float64(10), int64(2)
memory usage: 93.9 KB


In [96]:
df.isnull().sum()

Unnamed: 0      0
WTT             0
PTI             0
EQW             0
SBI             0
LQE             0
QWG             0
FDJ             0
PJF             0
HQE             0
NXJ             0
TARGET CLASS    0
dtype: int64

In [97]:
X = df.drop('TARGET CLASS', axis=1)

In [98]:
X

Unnamed: 0       WTT       PTI       EQW       SBI       LQE       QWG  \
0             0  0.913917  1.162073  0.567946  0.755464  0.780862  0.352608   
1             1  0.635632  1.003722  0.535342  0.825645  0.924109  0.648450   
2             2  0.721360  1.201493  0.921990  0.855595  1.526629  0.720781   
3             3  1.234204  1.386726  0.653046  0.825624  1.142504  0.875128   
4             4  1.279491  0.949750  0.627280  0.668976  1.232537  0.703727   
..          ...       ...       ...       ...       ...       ...       ...   
995         995  1.010953  1.034006  0.853116  0.622460  1.036610  0.586240   
996         996  0.575529  0.955786  0.941835  0.792882  1.414277  1.269540   
997         997  1.135470  0.982462  0.781905  0.916738  0.901031  0.884738   
998         998  1.084894  0.861769  0.407158  0.665696  1.608612  0.943859   
999         999  0.837460  0.961184  0.417006  0.799784  0.934399  0.424762   

          FDJ       PJF       HQE       NXJ  
0    0.759697  0.643798  0.879422  1.231409  
1    0.675334  1.013546  0.621552  1.492702  
2    1.626351  1.154483  0.957877  1.285597  
3    1.409708  1.380003  1.522692  1.153093  
4    1.115596  0.646691  1.463812  1.419167  
..        ...       ...       ...       ...  
995  0.746811  0.319752  1.117340  1.348517  
996  1.055928  0.713193  0.958684  1.663489  
997  0.386802  0.389584  0.919191  1.385504  
998  0.855806  1.061338  1.277456  1.188063  
999  0.778234  0.907962  1.257190  1.364837  

[1000 rows x 11 columns]

### Standardize the Variables
Because the KNN classifier predicts the class of a given test observation by identifying the observations that are nearest to it, the scale of the variables matters. Any variables that are on a large scale will have a much larger effect on the distance between the observations, and hence on the KNN classifier, than variables that are on a small scale.

In [99]:
from sklearn.preprocessing import StandardScaler

In [100]:
scaler = StandardScaler()

In [101]:
scaler.fit(X)

StandardScaler()

In [102]:
scaled_values = scaler.transform(X)

In [103]:
print(scaled_values)

[[-1.73031962 -0.12354188  0.18590747 ... -1.48236813 -0.9497194
  -0.64331425]
 [-1.72685552 -1.08483602 -0.43034845 ... -0.20224031 -1.82805088
   0.63675862]
 [-1.72339142 -0.78870217  0.33931821 ...  0.28570652 -0.68249379
  -0.37784986]
 ...
 [ 1.72339142  0.64177714 -0.51308341 ... -2.36249443 -0.81426092
   0.11159651]
 [ 1.72685552  0.46707241 -0.98278576 ... -0.03677699  0.40602453
  -0.85567   ]
 [ 1.73031962 -0.38765353 -0.59589427 ... -0.56778932  0.3369971
   0.01034996]]


In [104]:
X = pd.DataFrame(scaled_values,columns=X.columns)

In [105]:
y = df['TARGET CLASS']

In [106]:
X = X.drop('Unnamed: 0',axis=1)

In [107]:
X

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0   -0.123542  0.185907 -0.913431  0.319629 -1.033637 -2.308375 -0.798951   
1   -1.084836 -0.430348 -1.025313  0.625388 -0.444847 -1.152706 -1.129797   
2   -0.788702  0.339318  0.301511  0.755873  2.031693 -0.870156  2.599818   
3    0.982841  1.060193 -0.621399  0.625299  0.452820 -0.267220  1.750208   
4    1.139275 -0.640392 -0.709819 -0.057175  0.822886 -0.936773  0.596782   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.211653 -0.312490  0.065163 -0.259834  0.017567 -1.395721 -0.849486   
996 -1.292453 -0.616901  0.369613  0.482648  1.569891  1.273495  0.362784   
997  0.641777 -0.513083 -0.179205  1.022255 -0.539703 -0.229680 -2.261339   
998  0.467072 -0.982786 -1.465194 -0.071465  2.368666  0.001269 -0.422041   
999 -0.387654 -0.595894 -1.431398  0.512722 -0.402552 -2.026512 -0.726253   

          PJF       HQE       NXJ  
0   -1.482368 -0.949719 -0.643314  
1   -0.202240 -1.828051  0.636759  
2    0.285707 -0.682494 -0.377850  
3    1.066491  1.241325 -1.026987  
4   -1.472352  1.040772  0.276510  
..        ...       ...       ...  
995 -2.604264 -0.139347 -0.069602  
996 -1.242110 -0.679746  1.473448  
997 -2.362494 -0.814261  0.111597  
998 -0.036777  0.406025 -0.855670  
999 -0.567789  0.336997  0.010350  

[1000 rows x 10 columns]

In [108]:
from sklearn.model_selection import train_test_split

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [110]:
from sklearn.neighbors import KNeighborsClassifier

In [111]:
knn = KNeighborsClassifier(n_neighbors=1)

In [112]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [113]:
y_pred = knn.predict(X_test)

In [114]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1])

In [115]:
from sklearn.metrics import classification_report,confusion_matrix

In [116]:
confusion_matrix(y_test,y_pred)

array([[150,  14],
       [ 10, 126]])

In [117]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.91      0.93       164
           1       0.90      0.93      0.91       136

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



In [118]:
from sklearn.metrics import accuracy_score

In [119]:
accuracy_score(y_test,y_pred)

0.92

In [123]:
from sklearn.model_selection import cross_val_score

In [127]:
error_rate =[]

for i in range(1,40):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i=knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))
    
error_rate

[0.08,
 0.09666666666666666,
 0.07,
 0.07,
 0.08333333333333333,
 0.07666666666666666,
 0.08666666666666667,
 0.07666666666666666,
 0.08333333333333333,
 0.07666666666666666,
 0.08333333333333333,
 0.08,
 0.08333333333333333,
 0.07666666666666666,
 0.07666666666666666,
 0.07333333333333333,
 0.07666666666666666,
 0.07666666666666666,
 0.07333333333333333,
 0.06666666666666667,
 0.07,
 0.07666666666666666,
 0.07,
 0.07333333333333333,
 0.07333333333333333,
 0.07333333333333333,
 0.07,
 0.07333333333333333,
 0.07,
 0.07,
 0.07,
 0.07333333333333333,
 0.07,
 0.07333333333333333,
 0.07333333333333333,
 0.07666666666666666,
 0.07333333333333333,
 0.07333333333333333,
 0.07]

In [129]:
plt.figure(figsize=(10,6))
#plt.plot(range(1,40),error_rate,color='blue', linestyle='dashed', marker='o',
  #       markerfacecolor='red', markersize=10)
plt.plot(range(1,40),error_rate,color='blue', linestyle='dashed', marker='o',
         markerfacecolor='red', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

Text(0, 0.5, 'Error Rate')

In [133]:
knn = KNeighborsClassifier(n_neighbors=23)
knn.fit(X_train,y_train)
knn.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[150  14]
 [ 10 126]]
              precision    recall  f1-score   support

           0       0.94      0.91      0.93       164
           1       0.90      0.93      0.91       136

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

