# Logistic regression
Logistic Regression is a classification algorithm that models the probability of a certain class or category. It's often used when the dependent variable is binary (two classes), although it can be extended to handle multiple classes with techniques like one-vs-rest or softmax regression.

1. Used for binary classification
2. Classification but still called regression
3. Linear regression creates a best fit line
4. However, linear regression cannot be used for classification problems due to its limitations (sensetive to outliers)
5. To overcome this limitation, we use logistic regression
6. Logistic regression also creates a bestfit line
7. However, it deals well with the outliers with the help of signmoid function
8. It also handles multiclass models well creating multiple models
9. When a new data point is entered it enters in all the models and then results in a probability
10. The model with the highest probability is selected
11. Model as in the best fit line is chosen
12. Misclassification is inevitable. However, the distance between the line and the misclassified object is also considered.
13. Total distance between the misclassified points to the boundary (best fit line)
14. Line with the shortest distance is chosen


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
df = sns.load_dataset('Iris')

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
from sklearn.model_selection import train_test_split


In [8]:
X = df.drop('species', axis = 1)
y = df.species

In [11]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8)

In [14]:
model.fit(X_train, y_train)

/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
y_predicted = model.predict(X_test)

In [16]:
y_predicted

array(['setosa', 'virginica', 'virginica', 'versicolor', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'virginica', 'setosa', 'virginica', 'versicolor', 'virginica',
       'setosa', 'virginica', 'versicolor', 'virginica', 'virginica'],
      dtype=object)

In [18]:
sample = np.array([4.1, 3.2, 4.2, 6.2]).reshape(1, -1) #reshape to one row - sample 
model.predict(sample)

/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['virginica'], dtype=object)

In [19]:
sample = np.array([4.1, 3.2, 1.2, 0.2]).reshape(1,-1) #reshape to one row - sample 
model.predict(sample)

/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['setosa'], dtype=object)

In [20]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_test, y_predicted)
cf = classification_report(y_test, y_predicted)

In [24]:
print(cm)

[[ 7  0  0]
 [ 0  9  2]
 [ 0  2 10]]


In [23]:
print(cf)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         7
  versicolor       0.82      0.82      0.82        11
   virginica       0.83      0.83      0.83        12

    accuracy                           0.87        30
   macro avg       0.88      0.88      0.88        30
weighted avg       0.87      0.87      0.87        30

